// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcSclWkzj3tmZjtlKq8hEx-U_QErGn_I',
    appId: '1:537376963526:web:3f7c201ae3244154b050c7',
    messagingSenderId: '537376963526',
    projectId: 'testauthflutter10',
    authDomain: 'testauthflutter10.firebaseapp.com',
    storageBucket: 'testauthflutter10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdnURSwXJmwrd9m5jIuAXrJvpU0KXSlcw',
    appId: '1:537376963526:android:7472ea8bf51ed5dbb050c7',
    messagingSenderId: '537376963526',
    projectId: 'testauthflutter10',
    storageBucket: 'testauthflutter10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1k0Qs5TXSLFmZbfmQfMOBv5RdvBmD6Aw',
    appId: '1:537376963526:ios:2195beec5fc54ea5b050c7',
    messagingSenderId: '537376963526',
    projectId: 'testauthflutter10',
    storageBucket: 'testauthflutter10.appspot.com',
    iosBundleId: 'com.example.firebaseAuthTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1k0Qs5TXSLFmZbfmQfMOBv5RdvBmD6Aw',
    appId: '1:537376963526:ios:4b47deddee59de74b050c7',
    messagingSenderId: '537376963526',
    projectId: 'testauthflutter10',
    storageBucket: 'testauthflutter10.appspot.com',
    iosBundleId: 'com.example.firebaseAuthTest.RunnerTests',
  );
}
